# Build the module.
steps:
  - id: lint
    name: "gcr.io/cloud-builders/go"
    args: ["vet","./..."]
    env: ["PROJECT_ROOT=the-gpl"]
  - id: build
    name: "gcr.io/cloud-builders/docker"
    args: ['build', '--tag=gcr.io/the-gpl/hk', '.']
    env: ["PROJECT_ROOT=the-gpl"]
images: ['gcr.io/the-gpl/hk']
